name: Deploy to Fly
on: 
  push:
    branches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
      users: actions/checkout@v3
      - name: Install Fly
      users: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only --strategy immediate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}